name: "CI"
on:
  push:
    tags:
      - "*"
    branches:
      - "main"
  pull_request:

jobs:
  test:
    name: "Run unit tests"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        go-version: ["1.16.x", "1.15.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: go test ./... -v

  coverage:
    name: "Generate code coverage"
    runs-on: "ubuntu-latest"
    needs: "test"
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Coverage
      run: go test ./core/... ./utils/... -v -covermode=count -coverprofile=coverage.out

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.5

    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage.lcov
